# Generated by Django 5.0.3 on 2024-05-30 14:25

import creator.helpers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('message_permission', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1500)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=False, verbose_name='Is this a free post?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.tier')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=creator.helpers.get_upload_to)),
                ('type', models.CharField(editable=False, max_length=10)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='creator.post')),
                ('tier', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.tier')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tier_name_per_user'),
        ),
    ]
