version: '3.9'

services:
  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    volumes:
      - .:/usr/src/51442_52661_54362
    environment:
      - PYTHONUNBUFFERED=1

  pgdb:
    image: postgres:latest
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
