# Generated by Django 5.0.3 on 2025-05-27 21:20

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_content_creator',
            field=models.BooleanField(default=False, verbose_name='Вы автор?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_instagram_url], verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_twitter_url], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
    ]
