# Generated by Django 5.0.3 on 2025-06-16 23:51

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_is_content_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_instagram_url], verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[account.validators.validate_twitter_url], verbose_name='YouTube'),
        ),
    ]
